apiVersion: example.example.com/v1
kind: ConfigMapSync
metadata:
  labels:
    app.kubernetes.io/name: configmapsync
    app.kubernetes.io/instance: configmapsync-sample
    app.kubernetes.io/part-of: configmap-sync-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: configmap-sync-operator
  name: configmapsync-sample
spec:
  # TODO(user): Add fields here
